# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a06387a19c8b4155e161c562d54e13e9dcbe7cd2718a425d311e6ec1176e0328c7fd59ba392a703f32f2f25aff8cfc447398ecc4fddf25e210ec54f12c419b0

test:
  secret_key_base: 1a1951d32369d10fc778b4de2ba85a3fabc1ae267790b8a1a6322a6b37d5c4817841d16b309766469179ac83828a753eb95d1f8fda5f20f84b1624f3a51a15a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
